pipeline {

    agent{
        docker{
            image 'python:2.7.16-slim'
            args '-v $HOME/.m2:/root/.m2'
            args '--user root'
        }
    }
    
    stages{
        stage('build'){
            when { changeset "**/vote/**" }
            steps{
                echo 'Compiling'
                dir('vote'){
                    sh 'pip install -r requirements.txt'}
            }
        }
        stage('test'){
            when { changeset "**/vote/**" }
            steps{
                echo 'Testing'              
                dir('vote'){
                    sh 'nosetests -v'}
            }
        }
    }

    post{
        always{
            echo 'Complete!'
        }
    }
}