pipeline {

    agent none
    
    stages{
        stage('build'){
            agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '-v $HOME/.m2:/root/.m2'
                    args '--user root'
                }
            }
            when { changeset "**/vote/**" }
            steps{
                echo 'Compiling'
                dir('vote'){
                    sh 'pip install -r requirements.txt'}
            }
        }

        stage('test'){
            agent{
                docker{
                    image 'python:2.7.16-slim'
                    args '-v $HOME/.m2:/root/.m2'
                    args '--user root'
                }
            }
            when { changeset "**/vote/**" }
            steps{
                echo 'Testing'              
                dir('vote'){
                    sh 'nosetests -v'}
            }
        }

        stage('docker-package'){
            agent any
            when { 
                changeset "**/vote/**" 
                // branch 'master'
            }
            steps{
                echo 'Packaging with Docker'       
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerPW') {
                        def voteImage = docker.build("danielclough/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push()
                        voteImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }

    }

    post{
        always{
            echo 'Complete!'
        }
    }
}