version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - instavote

  vote:
    image: danielclough/vote:master
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote

  result:
    image:  danielclough/result:master
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: danielclough/worker:master
    depends_on:
      - redis
      - db
    networks:
      - instavote
