pipeline {
    agent{
        docker{
            image 'maven:3.6.1-jdk-8-slim'
        }
    }
    
    stages{
        stage('build'){
            steps{
                echo 'Compiling'
                dir('worker'){
                    sh 'mvn -eX compile'}
            }
        }
        stage('test'){
            steps{
                echo 'Testing'              
                dir('worker'){
                    sh 'mvn -e clean test'}
            }
        }
        stage('package'){
            steps{
                echo 'Packaging '       
                dir('worker'){
                    sh 'mvn -X package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }         
            }
        }
    }
    post{
        always{
            echo 'Complete!'
        }
    }
}