pipeline {

    agent{
        docker{
            image 'maven:3.6.1-jdk-8-slim'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    
    stages{
        stage('build'){
            steps{
                echo 'Compiling'
                dir('worker'){
                    sh 'mvn -e compile'}
            }
        }
        stage('test'){
            steps{
                echo 'Testing'              
                dir('worker'){
                    sh 'mvn -e clean test'}
            }
        }
        stage('package'){
            steps{
                echo 'Packaging '       
                dir('worker'){
                    sh 'mvn -e package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }         
            }
        }
    }

    post{
        always{
            echo 'Complete!'
        }
    }
}